### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JRud52** [xTVaser/it-group-project#1]
# The following tasks in regard to content still need to be completed:
For the main content, you can just replace the Lorem ipsum with some actual mock content. Just make something up pertaining to Richard Stallman(like Free and Open Source Software, Proprietary software is bad, that kind of thing).

## ALL
When the project is done, **everyone** needs to upload it to turing. Don't make it your index.html; link Mike to it instead using this link: http://turing.algomau.ca/~USERNAME/rstallman.html replacing USERNAME with your algomau login username.

> @wsigouin 
- [x] - Main content for the *index* page
- [x] - Main content for the *academics* page

> @Ravenspawn14 
- [x] - Main content for the *faculty* page
- [x] - Main content for the *teaching* page

> @xTVaser @JRud52
- [x] - Main content for the *research* page, see issue #2 
- [x] - Fix up the CSS on all pages to look more like it is an Algoma U Faculty page.

**Comment by wsigouin** [comment]
He says in the assignment that the content can be Ipsum, are we just trying to format it in some way? Or do we want to create actual content?

**Comment by xTVaser** [comment]
this is just nice

**Comment by xTVaser** [comment]
what are you thinking of for the CSS issues, move discussion to #3
