### ISSUE TITLE
CSS TODO List

### ISSUE THREAD

**Issue by xTVaser** [xTVaser/it-group-project#3]
- [ ] - pretty up the nav
- [ ] - tweak the colors a bit
- [x] - fix some padding/margin issues on most of the content
- [x] - writ da kaud
- [x] - do the thing

**Comment by wsigouin** [comment]
I am working on making the nav a little prettier rn

**Comment by JRud52** [comment]
k just make sure that it still looks like the simon fraser website

**Comment by xTVaser** [comment]
but not exactly the same
